cloud:
  aws:
    credentials:
      access-key: AKIAXMCST5V3CUQYJVU7
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: hometrainingbucket
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error