cloud:
  aws:
    credentials:
      access-key: AKIAXMCST5V3BZAG2L5T
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: hometrainingbucket
    stack:
      auto: false

spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error